image: nqoki709/monolis_build:latest

stages:
  - lib_build
  - test
  - doxy_build
  - deploy

build_monolis:
  stage: lib_build
  script:
    - make FLAGS=DEBUG
  artifacts:
    paths:
      - bin
      - test

test_monolis:
  stage: test
  script:
    - cd test
    - ./run.CI.sh
  dependencies:
    - build_monolis

doxygen_monolis:
  stage: doxy_build
  script:
    - cd manual/fortran
    - doxygen
    - cd ../c
    - doxygen
  artifacts:
    paths:
      - manual

pages:
  stage: deploy
  dependencies:
    - doxygen_monolis
  script:
    - mkdir public
    - mv manual/fortran/html public/fortran
    - mv manual/c/html public/c
  artifacts:
    paths:
      - public
