image: nqoki709/monolis_build:latest

stages:
  - lib_build
  - test
  - doxy_build
  - deploy

build_monolis:
  stage: lib_build
  script:
    - make
  artifacts:
    paths:
      - test

test_monolis:
  stage: test
  script:
    - cd test
    - ./monolis_utils_test
    - mpirun --oversubscribe --allow-run-as-root -np 2 ./monolis_utils_test
  dependencies:
    - build_monolis

doxygen_monolis:
  stage: doxy_build
  script:
    - cd manual
    - doxygen
  artifacts:
    paths:
      - manual

pages:
  stage: deploy
  dependencies:
    - doxygen_monolis
  script:
    - mv manual/html public
  artifacts:
    paths:
      - public
