image: nqoki709/monolis_build:latest

stages:
  - lib_build
  - test
  - doxy_build
  - deploy

build_monolis:
  stage: lib_build
  script:
    - make FLAGS=DEBUG
  artifacts:
    paths:
      - bin
      - test

test_monolis:
  stage: test
  script:
    - cd test
    - ./run.CI.sh
  dependencies:
    - build_monolis

doxygen_monolis:
  stage: doxy_build
  script:
    - cd manual
    - doxygen
  artifacts:
    paths:
      - manual

pages:
  stage: deploy
  dependencies:
    - doxygen_monolis
  script:
    - mv manual/html public
  artifacts:
    paths:
      - public
